
export const RECOMENDED_BASKET = 'RECOMENDED_BASKET';
export const BESTSELLER_BASKET = 'BESTSELLER_BASKET';
export const SINGLEBOX_BASKET = 'SINGLEBOX_BASKET';
export const DISCOUNT_BASKETS = 'DISCOUNT_BASKETS';
export const MAIN_CATEGORIES = 'MAIN_CATEGORIES';


export const ADD_BASKET = 'ADD_BASKET';
export const UPDATE_BASKET = 'UPDATE_BASKET';
export const DELETE_BASKET = 'DELETE_BASKET';
export const EMPTY_CART = 'EMPTY_CART';

export const SAVE_SUBSCRIPTION = 'SAVE_SUBSCRIPTION';
export const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS';



export const GO_CAT_SCREEN = 'GO_CAT_SCREEN';
export const USER_ID = 'USER_ID';
export const USER_DATA = 'USER_DATA';
